name: goreleaser

on:
  push:
    branches:
    - master
    tags:
    - '**'

permissions:
  contents: write # create release

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Download Javascript files
        run: |
          wget https://cdn.tailwindcss.com -O frontend/js/tailwindcss.js
          wget https://cdn.jsdelivr.net/npm/react@18/umd/react.production.min.js -O frontend/js/react.production.min.js
          wget https://cdn.jsdelivr.net/npm/react-dom@18/umd/react-dom.production.min.js -O frontend/js/react-dom.production.min.js
          wget https://cdn.jsdelivr.net/npm/babel-standalone@6/babel.min.js -O frontend/js/babel.min.js

      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Upload assets
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: rclone-precache
          path: dist/*
